// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzgU62EDD21sk4Sv1ZQqLokvU6OUQNtR0',
    appId: '1:534563467617:web:6dad5007c496d98e47d520',
    messagingSenderId: '534563467617',
    projectId: 'pataniaapp',
    authDomain: 'pataniaapp.firebaseapp.com',
    storageBucket: 'pataniaapp.firebasestorage.app',
    measurementId: 'G-ZDMPXJ3HDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu_7mOdVt0IoHo_Hu8Hay78LU7x_nlfwY',
    appId: '1:534563467617:android:a857a147f003635847d520',
    messagingSenderId: '534563467617',
    projectId: 'pataniaapp',
    storageBucket: 'pataniaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3UTMbEtWWvvKwLtXn7Ixni5BPvOdsZCw',
    appId: '1:534563467617:ios:d2acb8c897953c2747d520',
    messagingSenderId: '534563467617',
    projectId: 'pataniaapp',
    storageBucket: 'pataniaapp.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3UTMbEtWWvvKwLtXn7Ixni5BPvOdsZCw',
    appId: '1:534563467617:ios:d2acb8c897953c2747d520',
    messagingSenderId: '534563467617',
    projectId: 'pataniaapp',
    storageBucket: 'pataniaapp.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzgU62EDD21sk4Sv1ZQqLokvU6OUQNtR0',
    appId: '1:534563467617:web:287027a3a28ed2df47d520',
    messagingSenderId: '534563467617',
    projectId: 'pataniaapp',
    authDomain: 'pataniaapp.firebaseapp.com',
    storageBucket: 'pataniaapp.firebasestorage.app',
    measurementId: 'G-FP91WJ3BHX',
  );

}